### ISSUE TITLE
[Bug]: kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized

### ISSUE THREAD

**Issue by Mo0Khaled** [sdurban/flutter_meta_appads_sdk#1]
I am getting the following error when I try to run on android device, btw IOS works just fine.

```
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): Failed to handle method call
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleGetApplicationId(FacebookAppEventsPlugin.kt:98)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:48)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.os.Looper.loopOnce(Looper.java:230)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.os.Looper.loop(Looper.java:319)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.app.ActivityThread.main(ActivityThread.java:8919)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): Failed to handle method call
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleLogEvent(FacebookAppEventsPlugin.kt:122)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:49)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.os.Looper.loopOnce(Looper.java:230)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.os.Looper.loop(Looper.java:319)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at android.app.ActivityThread.main(ActivityThread.java:8919)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(27484): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by Mo0Khaled** [comment]
Sorry my bad, i shouldn't enable auto init on the manifest file and also call the init function, I should do only one either this or this.
